/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;
import query.Q10;
import query.Q2;
import query.Q3;
import query.Q9;
import entity.Product;
import entity.Evaluates;
import entity.Returned;
import entity.Ticket;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jesus
 */
public class HHRR_Manager extends javax.swing.JFrame {

    private static String contra;
    private static String usuario;

    /**
     * Creates new form NewJFrame
     * @param usuarioo
     * @param contraa
     */
    public HHRR_Manager(String usuarioo, String contraa) {
        initComponents();
        this.setTitle("HHRR_Manager");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        HHRR_Manager.contra = contraa;
        HHRR_Manager.usuario = usuarioo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadoTextArea = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        rBinsert = new javax.swing.JRadioButton();
        rBselect = new javax.swing.JRadioButton();
        rBupdate = new javax.swing.JRadioButton();
        rBdelete = new javax.swing.JRadioButton();
        rBdeleteOne = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rProduct = new javax.swing.JRadioButton();
        rPurchased = new javax.swing.JRadioButton();
        rTicket = new javax.swing.JRadioButton();
        rReturned = new javax.swing.JRadioButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        bsiguiente = new javax.swing.JButton();
        BComeON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton24.setBackground(new java.awt.Color(255, 0, 51));
        jButton24.setText("Query4");
        jButton24.setToolTipText("4.Obtain the total money billed by the supermarket since the implementation of the database.  ");
        jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton24MouseClicked(evt);
            }
        });
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 36, 81, -1));

        jButton25.setBackground(new java.awt.Color(255, 0, 51));
        jButton25.setText("Query5");
        jButton25.setToolTipText("5. Show customer coupons, along with the products they affect and the discount made ");
        jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton25MouseClicked(evt);
            }
        });
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 36, 81, -1));

        jButton26.setBackground(new java.awt.Color(255, 0, 51));
        jButton26.setText("Query6");
        jButton26.setToolTipText("6. Show 5 products on which members have discount coupons  ");
        jButton26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton26MouseClicked(evt);
            }
        });
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 113, 81, -1));

        jButton27.setBackground(new java.awt.Color(255, 0, 51));
        jButton27.setText("Query7");
        jButton27.setToolTipText("7. Determine the average degree of satisfaction of the opinions that customers have made online, showing the average score. ");
        jButton27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton27MouseClicked(evt);
            }
        });
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 81, -1));

        jButton28.setText("Query9");
        jButton28.setToolTipText("9. Determine the number of workers each supermarket has, ordering the exit from lowest to highest. ");
        jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton28MouseClicked(evt);
            }
        });
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 81, -1));

        jButton29.setBackground(new java.awt.Color(255, 0, 51));
        jButton29.setText("Query8");
        jButton29.setToolTipText(" 8. Determine the number of tickets that each supermarket has issued, showing the number of tickets, the name of the cashier and the city of the supermarket where the cashier works. Sort the output from highest to lowest. ");
        jButton29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton29MouseClicked(evt);
            }
        });
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 81, -1));

        jButton30.setText("Query10");
        jButton30.setToolTipText("10. Show the name and telephone number of the employee with the best score ");
        jButton30.setMinimumSize(null);
        jButton30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton30MouseClicked(evt);
            }
        });
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, -1, -1));

        jButton15.setBackground(new java.awt.Color(255, 0, 51));
        jButton15.setText("Query17");
        jButton15.setToolTipText("17. Show the name of the member that has issued the best opinion (the highest score) ");
        jButton15.setMinimumSize(null);
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 260, -1, -1));

        jButton16.setBackground(new java.awt.Color(255, 0, 51));
        jButton16.setText("Query18");
        jButton16.setToolTipText("18. Show the tickets issued by cashiers whose name begins with “A” and works in cities that begin with “M” ");
        jButton16.setMinimumSize(null);
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        jButton10.setBackground(new java.awt.Color(255, 0, 51));
        jButton10.setText("Query16");
        jButton10.setToolTipText("16. Show the name of the cashier that has issued the most tickets ");
        jButton10.setMinimumSize(null);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jButton11.setBackground(new java.awt.Color(255, 0, 51));
        jButton11.setText("Query11");
        jButton11.setToolTipText("11. Show the barcode and the discount of the products that were on sale the first week of May 2019. ");
        jButton11.setMinimumSize(null);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jButton12.setBackground(new java.awt.Color(255, 0, 51));
        jButton12.setText("Query12");
        jButton12.setToolTipText("12. Show the name of the members who have benefited from discounts applied to a product the last week of May 2019 ");
        jButton12.setMinimumSize(null);
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 190, -1, -1));

        jButton13.setBackground(new java.awt.Color(255, 0, 51));
        jButton13.setText("Query13");
        jButton13.setToolTipText("13. Show the name of the workers in alphabetical order of the supermarkets located in cities that begin with “M”. ");
        jButton13.setMinimumSize(null);
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 190, -1, -1));

        jButton14.setBackground(new java.awt.Color(255, 0, 51));
        jButton14.setText("Query15");
        jButton14.setToolTipText("15. Show the product that has been returned the most times.  ");
        jButton14.setMinimumSize(null);
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, -1, -1));

        jButton22.setBackground(new java.awt.Color(255, 0, 51));
        jButton22.setText("Query14");
        jButton22.setToolTipText("14. Show the email of the member whose total amount accumulated is the highest ");
        jButton22.setMinimumSize(null);
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton22MouseClicked(evt);
            }
        });
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 190, -1, -1));

        jButton19.setBackground(new java.awt.Color(255, 0, 51));
        jButton19.setText("Query1");
        jButton19.setToolTipText("1. Obtain the items in the database, showing the barcode and the price without VAT.");
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton19MouseClicked(evt);
            }
        });
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 36, 81, -1));

        jButton21.setText("Query2");
        jButton21.setToolTipText("2. Obtain the name of every worker indicating if they are cashiers or repleteners. ");
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton21MouseClicked(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 81, -1));

        jButton17.setBackground(new java.awt.Color(255, 0, 51));
        jButton17.setText("Query19");
        jButton17.setToolTipText("19. Show the id of the tickets issued in the supermarkets of Alcalá de Henares along with the name of the cashier ");
        jButton17.setMinimumSize(null);
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 260, -1, -1));

        jButton23.setText("Query3");
        jButton23.setToolTipText("3.  Obtain the name of the repleteners who work more than 20 hours per week. ");
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton23MouseClicked(evt);
            }
        });
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 81, -1));

        jButton18.setBackground(new java.awt.Color(255, 0, 51));
        jButton18.setText("Query20");
        jButton18.setToolTipText("20. Perform the same query as the previous point but for those tickets in which no discount coupons have been used ");
        jButton18.setMinimumSize(null);
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 260, -1, -1));

        resultadoTextArea.setColumns(20);
        resultadoTextArea.setRows(5);
        jScrollPane1.setViewportView(resultadoTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 710, -1));

        jButton2.setText("ATRÁS");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 630, -1, -1));

        rBinsert.setText("Insert");
        rBinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBinsertActionPerformed(evt);
            }
        });
        getContentPane().add(rBinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        rBselect.setText("Select");
        rBselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBselectActionPerformed(evt);
            }
        });
        getContentPane().add(rBselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, -1));

        rBupdate.setText("Update");
        rBupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBupdateActionPerformed(evt);
            }
        });
        getContentPane().add(rBupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        rBdelete.setText("Delete all");
        rBdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(rBdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, -1));

        rBdeleteOne.setText("Delete one");
        rBdeleteOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rBdeleteOneMouseClicked(evt);
            }
        });
        rBdeleteOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBdeleteOneActionPerformed(evt);
            }
        });
        getContentPane().add(rBdeleteOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("SCRIPT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("ENTITIES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        rProduct.setText("Product");
        rProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rProductActionPerformed(evt);
            }
        });
        getContentPane().add(rProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, -1));

        rPurchased.setText("Evaluates");
        rPurchased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPurchasedActionPerformed(evt);
            }
        });
        getContentPane().add(rPurchased, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, -1, -1));

        rTicket.setText("Ticket");
        rTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTicketActionPerformed(evt);
            }
        });
        getContentPane().add(rTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, -1));

        rReturned.setText("Returned");
        rReturned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rReturnedActionPerformed(evt);
            }
        });
        getContentPane().add(rReturned, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, -1, -1));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 210, -1));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 210, -1));

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 210, -1));

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 210, -1));
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 210, -1));
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 210, -1));
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 210, -1));
        getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 210, -1));

        bsiguiente.setText("NEXT");
        bsiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bsiguienteMouseClicked(evt);
            }
        });
        getContentPane().add(bsiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, -1, -1));

        BComeON.setText("COME ON");
        BComeON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BComeONMouseClicked(evt);
            }
        });
        getContentPane().add(BComeON, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseClicked
        
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton19MouseClicked

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");        
    }//GEN-LAST:event_jButton24MouseClicked

    private void jButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton25MouseClicked

    private void jButton26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton26MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton26MouseClicked

    private void jButton27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton27MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton27MouseClicked

    private void jButton29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton29MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton29MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton22MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton17MouseClicked

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "No tienes permiso de acceso");
    }//GEN-LAST:event_jButton18MouseClicked

    private void jButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseClicked
        // Q2
        String resul = Q2.q2(usuario, contra);   
        resultadoTextArea.setText(resul);
    }//GEN-LAST:event_jButton21MouseClicked

    private void jButton23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseClicked
        // Q3
        String resul = Q3.q3(usuario, contra);   
        resultadoTextArea.setText(resul);
    }//GEN-LAST:event_jButton23MouseClicked

    private void jButton28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MouseClicked
        // Q9
        String resul = Q9.q9(usuario, contra);   
        resultadoTextArea.setText(resul);
    }//GEN-LAST:event_jButton28MouseClicked

    private void jButton30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton30MouseClicked
        // Q10
        String resul = Q10.q10(usuario, contra);   
        resultadoTextArea.setText(resul);
    }//GEN-LAST:event_jButton30MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rBinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBinsertActionPerformed
        // TODO add your handling code here:
        if (rBinsert.isSelected()){
            rBselect.setSelected(false);
            rBupdate.setSelected(false);
            rBdelete.setSelected(false);
            rBdeleteOne.setSelected(false);
        }
    }//GEN-LAST:event_rBinsertActionPerformed

    private void rBselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBselectActionPerformed
        // TODO add your handling code here:
        if (rBselect.isSelected()){
            rBinsert.setSelected(false);
            rBupdate.setSelected(false);
            rBdelete.setSelected(false);
            rBdeleteOne.setSelected(false);
        }
    }//GEN-LAST:event_rBselectActionPerformed

    private void rBupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBupdateActionPerformed
        // TODO add your handling code here:
        if (rBupdate.isSelected()){
            rBinsert.setSelected(false);
            rBselect.setSelected(false);
            rBdelete.setSelected(false);
            rBdeleteOne.setSelected(false);
        }
    }//GEN-LAST:event_rBupdateActionPerformed

    private void rBdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBdeleteActionPerformed
        // TODO add your handling code here:
        if (rBdelete.isSelected()){
            rBinsert.setSelected(false);
            rBselect.setSelected(false);
            rBupdate.setSelected(false);
            rBdeleteOne.setSelected(false);
        }
    }//GEN-LAST:event_rBdeleteActionPerformed

    private void rBdeleteOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rBdeleteOneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rBdeleteOneMouseClicked

    private void rBdeleteOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBdeleteOneActionPerformed
        // TODO add your handling code here:
        if ( rBdeleteOne.isSelected()){
            rBselect.setSelected(false);
            rBupdate.setSelected(false);
            rBdelete.setSelected(false);
            rBinsert.setSelected(false);
        }
    }//GEN-LAST:event_rBdeleteOneActionPerformed

    private void rProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rProductActionPerformed
        // TODO add your handling code here:
        if (rProduct.isSelected()){
            rPurchased.setSelected(false);
            rReturned.setSelected(false);
            rTicket.setSelected(false);
        }
    }//GEN-LAST:event_rProductActionPerformed

    private void rPurchasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPurchasedActionPerformed
        // TODO add your handling code here:
        if (rPurchased.isSelected()){
            rProduct.setSelected(false);
            rReturned.setSelected(false);
            rTicket.setSelected(false);
        }
    }//GEN-LAST:event_rPurchasedActionPerformed

    private void rTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTicketActionPerformed
        // TODO add your handling code here:
        if (rTicket.isSelected()){
            rProduct.setSelected(false);
            rReturned.setSelected(false);
            rPurchased.setSelected(false);
        }
    }//GEN-LAST:event_rTicketActionPerformed

    private void rReturnedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rReturnedActionPerformed
        // TODO add your handling code here:
        if (rReturned.isSelected()){
            rProduct.setSelected(false);
            rTicket.setSelected(false);
            rPurchased.setSelected(false);
        }
    }//GEN-LAST:event_rReturnedActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed

    }//GEN-LAST:event_t1ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void bsiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bsiguienteMouseClicked
        // product
        float i = (float)25;
        if (rProduct.isSelected()){
            if (rBinsert.isSelected()){
                try {
                    JOptionPane.showMessageDialog(this,
                        Product.insert(usuario, contra,
                            Integer.parseInt(t1.getText()),
                            t2.getText(), Integer.parseInt(t3.getText()), i, Integer.parseInt(t4.getText()),
                            Integer.parseInt(t5.getText()), t6.getText(),
                            t7.getText()));
                } catch (SQLException ex) {
                    Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (rBdelete.isSelected()){
                JOptionPane.showMessageDialog(this, Product.delete(usuario, contra));
            } else if (rBdeleteOne.isSelected()){
                JOptionPane.showMessageDialog(this, Product.delete_one(usuario,
                    contra, Integer.parseInt(t1.getText())));
        } else if (rBupdate.isSelected()){
            JOptionPane.showMessageDialog(this, Product.update(usuario, contra,
                Integer.parseInt(t1.getText()), t2.getText()));
        } else if (rBselect.isSelected()){
            JOptionPane.showMessageDialog(this, Product.select(usuario, contra));
        }
        }
        // purchased
        else if (rPurchased.isSelected()){
            if (rBinsert.isSelected()){
                JOptionPane.showMessageDialog(this, Evaluates.insert(usuario,
                    contra, t1.getText(), t2.getText(),
                    Integer.parseInt(t3.getText())));
        } else if (rBdelete.isSelected()){
            JOptionPane.showMessageDialog(this, Evaluates.delete(usuario, contra));
        } else if (rBdeleteOne.isSelected()){
            JOptionPane.showMessageDialog(this, Evaluates.delete_one(usuario,
                contra, t1.getText()));
        } else if (rBupdate.isSelected()){
            JOptionPane.showMessageDialog(this, Evaluates.update(usuario,
                contra, t1.getText(), Integer.parseInt(t3.getText())));
        } else if (rBselect.isSelected()){
            JOptionPane.showMessageDialog(this, Evaluates.select(usuario, contra));
        }
        }
        // ticket
        else if (rTicket.isSelected()){
            if (rBinsert.isSelected()){
                JOptionPane.showMessageDialog(this, Ticket.insert(usuario, contra,
                    t1.getText(), t2.getText(), t3.getText(), false,
                    Integer.parseInt(t4.getText()), Integer.parseInt(t5.getText()),
                    t6.getText(), Integer.parseInt(t7.getText()), false, Integer.parseInt(t8.getText())));
        } else if (rBdelete.isSelected()){
            JOptionPane.showMessageDialog(this, Ticket.delete(usuario, contra));
        } else if (rBdeleteOne.isSelected()){
            JOptionPane.showMessageDialog(this, Ticket.delete_one(usuario,
                contra, t1.getText()));
        } else if (rBupdate.isSelected()){
            JOptionPane.showMessageDialog(this, Ticket.update(usuario,
                contra, Integer.parseInt(t1.getText()), Integer.parseInt(t2.getText())));
        } else if (rBselect.isSelected()){
            JOptionPane.showMessageDialog(this, Ticket.select(usuario, contra));
        }
        }
        // returned
        else if (rReturned.isSelected()){
            if (rBinsert.isSelected()){
                JOptionPane.showMessageDialog(this, Returned.insert(usuario,
                    contra, Integer.parseInt(t1.getText()),
                    Integer.parseInt(t2.getText()),
                    (float) Integer.parseInt(t3.getText())));
        } else if (rBdelete.isSelected()){
            JOptionPane.showMessageDialog(this, Returned.delete(usuario, contra));
        } else if (rBdeleteOne.isSelected()){
            JOptionPane.showMessageDialog(this, Returned.delete_one(usuario,
                contra, Integer.parseInt(t1.getText())));
        } else if (rBupdate.isSelected()){
            JOptionPane.showMessageDialog(this, Returned.update(usuario,
                contra, Integer.parseInt(t1.getText()),
                Integer.parseInt(t1.getText())));
        } else if (rBselect.isSelected()){
            JOptionPane.showMessageDialog(this, Returned.select(usuario, contra));
        }
        }
    }//GEN-LAST:event_bsiguienteMouseClicked

    private void BComeONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BComeONMouseClicked

        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        t7.setText("");
        t8.setText("");

        t1.setEditable(true);
        t2.setEditable(true);
        t3.setEditable(true);
        t4.setEditable(true);
        t5.setEditable(true);
        t6.setEditable(true);
        t7.setEditable(true);
        t8.setEditable(true);

        // product
        if (rProduct.isSelected()){
            if (rBinsert.isSelected()){
                t1.setText("Bar Code (int)");
                t2.setText("Name Product (String)");
                t3.setText("Price Not Vat (float)");
                t4.setText("Stock (int)");
                t5.setText("Week Discount (int)");
                t6.setText("Start Date (String)");
                t7.setText("End Date (String)");
                t8.setText("Price Vat will be calculated...");
            } else if (rBdelete.isSelected()){
                t1.setEditable(false);
                t2.setEditable(false);
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            } else if (rBdeleteOne.isSelected()){
                t1.setText("Bar Code (int)");
                t2.setEditable(false);
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            } else if (rBupdate.isSelected()){
                t1.setText("Bar Code (int)");
                t2.setText("Name Product (String)");
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            } else if (rBselect.isSelected()){
                t1.setEditable(false);
                t2.setEditable(false);
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            }
        }
        // purchased
        else if (rPurchased.isSelected()){
            if (rBinsert.isSelected()){
                t1.setText("ID Evaluador (String)");
                t2.setText("ID Evaluado(String)");
                t3.setText("Grade (int)");
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            } else if (rBdelete.isSelected()){
                t1.setEditable(false);
                t2.setEditable(false);
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            } else if (rBdeleteOne.isSelected()){
                t1.setText("ID Evaluador (String)");
                t2.setEditable(false);
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            } else if (rBupdate.isSelected()){
                t1.setText("ID Evaluador (String)");
                t2.setEditable(false);
                t3.setText("Grade (int)");
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            } else if (rBselect.isSelected()){
                t1.setEditable(false);
                t2.setEditable(false);
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            }
        }
        // ticket
        else if (rTicket.isSelected()){
            if (rBinsert.isSelected()){
                t1.setText("ID(String)");
                t2.setText("05-05-2015");
                t2.setEditable(false);
                t3.setText("15:15:15");
                t3.setEditable(false);
                t4.setText("Total price (float)");
                t5.setText("Amount Accumulated (float)");
                t6.setText("ID Cashier (String)");
                t7.setText("Member Code (int)");
                t8.setText("Quantity used (int)");
            } else if (rBdelete.isSelected()){
                t1.setEditable(false);
                t2.setEditable(false);
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            } else if (rBdeleteOne.isSelected()){
                t1.setText("ID(String)");
                t2.setEditable(false);
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            } else if (rBupdate.isSelected()){
                t1.setText("ID(String)");
                t2.setText("Total price (float)");
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            } else if (rBselect.isSelected()){
                t1.setEditable(false);
                t2.setEditable(false);
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            }
        }
        // returned
        else if (rReturned.isSelected()){
            if (rBinsert.isSelected()){
                t1.setText("Bar Code Product (int)");
                t2.setText("ID Ticket (int)");
                t3.setText("Amount (float)");
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            } else if (rBdelete.isSelected()){
                t1.setEditable(false);
                t2.setEditable(false);
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            } else if (rBdeleteOne.isSelected()){
                t1.setText("Bar Code Product (int)");
                t2.setEditable(false);
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            } else if (rBupdate.isSelected()){
                t1.setText("Bar Code Product (int)");
                t2.setText("Amount (int)");
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            } else if (rBselect.isSelected()){
                t1.setEditable(false);
                t2.setEditable(false);
                t3.setEditable(false);
                t4.setEditable(false);
                t5.setEditable(false);
                t6.setEditable(false);
                t7.setEditable(false);
                t8.setEditable(false);
            }
        }

    }//GEN-LAST:event_BComeONMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BComeON;
    private javax.swing.JButton bsiguiente;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rBdelete;
    private javax.swing.JRadioButton rBdeleteOne;
    private javax.swing.JRadioButton rBinsert;
    private javax.swing.JRadioButton rBselect;
    private javax.swing.JRadioButton rBupdate;
    private javax.swing.JRadioButton rProduct;
    private javax.swing.JRadioButton rPurchased;
    private javax.swing.JRadioButton rReturned;
    private javax.swing.JRadioButton rTicket;
    private javax.swing.JTextArea resultadoTextArea;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables
}
